#
# Copyright (c) 2020 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Network shell
CONFIG_SHELL=y
CONFIG_OPENTHREAD_SHELL=y
CONFIG_SHELL_ARGC_MAX=26
CONFIG_SHELL_CMD_BUFF_SIZE=416

# Increase Settings storage size
CONFIG_PM_PARTITION_SIZE_SETTINGS_STORAGE=0x8000

# Enable OpenThread features set
CONFIG_OPENTHREAD_NORDIC_LIBRARY_MASTER=y

# Generic networking options
CONFIG_OPENTHREAD=y
CONFIG_NET_L2_OPENTHREAD=y
CONFIG_NETWORKING=y

CONFIG_GPIO_SHELL=y

# Enable OpenThread support
CONFIG_OPENTHREAD_FTD=y  
CONFIG_OPENTHREAD_JOINER=y 

CONFIG_OPENTHREAD_CHANNEL=21
CONFIG_OPENTHREAD_NETWORKKEY="40c02e4d206abf9686d0dd58347a62d9"
CONFIG_OPENTHREAD_PANID=47766
CONFIG_OPENTHREAD_XPANID="0xc765dc72384f69e0"

# Enable IPv6 support
CONFIG_NET_IPV6=y
CONFIG_NET_IPV6_MLD=y

# USB and UART configuration (if needed for CLI or debugging)
CONFIG_USB_DEVICE_STACK=y
CONFIG_UART_LINE_CTRL=y

# Enable UDP
CONFIG_NET_UDP=y

# Increase buffer sizes for networking (optional, but useful for UDP packets)
CONFIG_NET_BUF_RX_COUNT=20
CONFIG_NET_BUF_TX_COUNT=20
CONFIG_NET_BUF_DATA_SIZE=128


CONFIG_HEAP_MEM_POOL_SIZE=2048  
CONFIG_NET_PKT_RX_COUNT=8
CONFIG_NET_PKT_TX_COUNT=8

# Enable CoAP
CONFIG_COAP=y
CONFIG_COAP_UTILS=y
CONFIG_OPENTHREAD_COAP=y  

CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_POSIX_NAMES=y
CONFIG_POLL=y

